version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vrgestaopdv-postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE:-test}
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vrgestaopdv-net

  vrgestaopdv-api:
    image: vrsoftbr/node:22.11.0-alpine-dev
    container_name: vrgestaopdv-api
    volumes:
      - '.:/home/node/app'
    entrypoint: ./.docker/entrypoint.sh
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-root}
      - DB_DATABASE=${DB_DATABASE:-test}
    ports:
      - '${PORT:-3000}:3000'
      - '7000:7000'
      - '9000:9000'
    networks:
      - vrgestaopdv-net

  vrgestorpdv-rabbitmq:
    build:
      context: ./.docker/rabbitmq
      dockerfile: Dockerfile
    container_name: vrgestorpdv-rabbitmq
    volumes:
      - ./db/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=vr
      - RABBITMQ_DEFAULT_PASS=vr!RbtMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - vrgestaopdv-net

    mem_limit: $MEM_LIMIT_API

volumes:
  postgres_data:
    driver: local
  node_modules:
    driver: local

networks:
  vrgestaopdv-net:
    name: vrgestaopdv-net
    driver: bridge
